import { chromium } from 'playwright-core';
import http from 'http';
import { readFile, writeFile } from 'fs/promises';
import path from 'path';
import { PNG } from 'pngjs';
const root='C:/Users/capit/rope-duel';
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.woff2':'font/woff2'};
const srv=http.createServer(async(req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]);if(p==='/')p='/index.html';
 try{const d=await readFile(path.join(root,p));res.writeHead(200,{'Content-Type':MIME[path.extname(p)]||'application/octet-stream'});res.end(d);}catch{res.writeHead(404);res.end('no');}});
await new Promise(r=>srv.listen(8990,r));
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await b.newPage({viewport:{width:1280,height:800}});
await page.goto('http://localhost:8990/?mode=demo&seed=11',{waitUntil:'load'});
await page.waitForTimeout(4000);
await page.evaluate(()=>window.__duelDebug.freeze(true,1.1,-1.1));
await page.waitForTimeout(700);
const r=await page.evaluate(()=>window.__duelPage.chart.stats().screen);
const A=await page.screenshot();
await page.evaluate(()=>window.__duelPage.chart.setVisible(false));
await page.waitForTimeout(500);
const B=await page.screenshot();
await page.evaluate(()=>window.__duelPage.chart.setVisible(true));
await page.waitForTimeout(300);
const C=await page.screenshot();
const st=await page.evaluate(()=>({q:window.__duelDebug.quality(), vis:window.__duelPage.chart.mesh.visible}));
const pa=PNG.sync.read(A),pb=PNG.sync.read(B),pc=PNG.sync.read(C);
const L=Math.round(r.l*pa.width),R=Math.round(r.r*pa.width),T=Math.round(r.t*pa.height),Bo=Math.round(r.b*pa.height);
let diff=0,tot=0,brightOn=0,brightOff=0;
const hist=(p)=>{const h=new Array(6).fill(0);let n=0;for(let y=T;y<Bo;y+=1)for(let x=L;x<R;x+=1){const i=(p.width*y+x)<<2;n++;const l=0.299*p.data[i]+0.587*p.data[i+1]+0.114*p.data[i+2];h[Math.min(5,Math.floor(l/42.5))]++;}return h.map(v=>+(100*v/n).toFixed(1));};
for(let y=T;y<Bo;y+=1)for(let x=L;x<R;x+=1){const i=(pa.width*y+x)<<2;tot++;
 const d=Math.abs(pa.data[i]-pb.data[i])+Math.abs(pa.data[i+1]-pb.data[i+1])+Math.abs(pa.data[i+2]-pb.data[i+2]);
 if(d>30)diff++;
 const la=0.299*pa.data[i]+0.587*pa.data[i+1]+0.114*pa.data[i+2];
 const lb=0.299*pb.data[i]+0.587*pb.data[i+1]+0.114*pb.data[i+2];
 if(la>170)brightOn++; if(lb>170)brightOff++;}
let idem=0; for(let y=T;y<Bo;y+=1)for(let x=L;x<R;x+=1){const i=(pa.width*y+x)<<2;const d=Math.abs(pa.data[i]-pc.data[i])+Math.abs(pa.data[i+1]-pc.data[i+1])+Math.abs(pa.data[i+2]-pc.data[i+2]);if(d>30)idem++;}
console.log(JSON.stringify({glass_on_vs_off_changedPct:+(100*diff/tot).toFixed(1), brightPixels_glassOn:brightOn, brightPixels_glassOff:brightOff, restoreIdempotentPct:+(100*idem/tot).toFixed(2), histGlassOn:hist(pa), histGlassOff:hist(pb), quality:st.q, sampled:tot},null,1));
await writeFile('tools/shots/chartfix_on.png',A); await writeFile('tools/shots/chartfix_off.png',B);
await b.close(); srv.close(); process.exit(0);
